name: Update Badges

on:
  workflow_dispatch:

jobs:
  update-readme:
    name: Update badges in README.md
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Badges - README.md
        uses: pemtajo/badge-readme@main
        with:       
          CREDLY_USER: lukas-gunnarsson
          BADGE_SIZE: 70x70
          COMMIT_MESSAGE: "Update badges"
